"""Story 7 — Jira Story Creation & Assignment: Verdict -> JiraTicket.

Default is DRY-RUN: renders the exact issue payload without calling Jira.
``--create`` posts to Jira DC (jirap) with the PAT, de-duplicating on a deterministic
label derived from (sourceRepo, commit, impactedRepo) — a rerun comments instead.
"""
from __future__ import annotations

import hashlib
import json
import ssl
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

from ..config import CONFIG, Config
from ..contracts import validate_jira_ticket

_CTX = ssl.create_default_context()
_CTX.check_hostname = False
_CTX.verify_mode = ssl.CERT_NONE


def dedupe_label(source_repo: str, commit: str, impacted: str) -> str:
    return "br-" + hashlib.sha1(f"{source_repo}|{commit}|{impacted}".lower().encode()).hexdigest()[:12]


def load_mapping(path: Path) -> dict:
    try:
        return yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError:
        return {}


def resolve_target(verdict: dict, mapping: dict, cfg: Config, project_override: str | None) -> dict:
    teams = {k.lower(): v for k, v in (mapping.get("teams") or {}).items()}
    repos = {k.lower(): v for k, v in (mapping.get("repos") or {}).items()}
    key = f"{verdict['org']}/{verdict['repo']}".lower()
    hit = repos.get(key) or teams.get((verdict.get("team") or "").lower())
    default = mapping.get("default") or {}
    if project_override:
        return {"project": project_override, "component": (hit or {}).get("component"), "assignee": (hit or {}).get("assignee"),
                "mapped": bool(hit), "note": "project overridden for testing"}
    if hit and hit.get("project"):
        return {"project": hit["project"], "component": hit.get("component"), "assignee": hit.get("assignee"), "mapped": True, "note": None}
    proj = default.get("project") or cfg.jira_triage_project or None
    return {"project": proj, "component": default.get("component", "unassigned"), "assignee": None, "mapped": False,
            "note": f"No jira-team-mapping entry for team {verdict.get('team')!r} / repo {key} — routed to shared triage."}


def render(verdict: dict, blast: dict, event: dict | None, target: dict, cfg: Config) -> dict:
    src, commit = blast["sourceRepo"], blast["commit"]
    short = commit[:8]
    web = cfg.github_web
    commit_url = f"{web}/{src}/commit/{commit}"
    pr = (event or {}).get("prNumber")
    pr_url = f"{web}/{src}/pull/{pr}" if pr else None
    tr = (verdict.get("evidence") or {}).get("testResult") or {}
    evs = (verdict.get("evidence") or {}).get("blastRadius") or []
    live = tr.get("hadLiveIntegrationSignal")
    caveat = ("(/) LIVE-INTEGRATION SIGNAL: the tests that ran exercise the changed service."
              if live else "(!) GENERIC SANITY CHECK ONLY: none of the tests that ran are known to exercise the changed service. "
                           "A pass does NOT prove no impact; a failure may be unrelated.")
    lines = [
        f"h2. Blast Radius: {src}@{short} may impact {verdict['org']}/{verdict['repo']}",
        f"*Verdict:* {verdict['verdict']}  |  *Blast-radius confidence:* {verdict.get('confidence')}  |  *Priority hint:* {verdict.get('priority')}",
        "",
        "h3. Source change",
        f"* Repo: [{src}|{web}/{src}]",
        f"* Commit: [{short}|{commit_url}]" + (f"  |  PR: [#{pr}|{pr_url}]" if pr_url else ""),
        f"* Environment: {(event or {}).get('environment', 'staging')}",
        "",
        "h3. Verdict reasoning",
        verdict["reasoning"],
        "",
        "h3. Test result",
        f"{{panel}}{caveat}{{panel}}",
        f"* Status: *{tr.get('status', 'n/a')}*" + (f" — {tr.get('skippedReason')}" if tr.get("skippedReason") else ""),
        f"* Failed tests: {', '.join(tr.get('failedTests') or []) or 'none'}",
        f"* Live-integration note: {tr.get('liveIntegrationNote') or 'n/a'}",
    ]
    if tr.get("logExcerpt"):
        lines += ["{noformat}", tr["logExcerpt"][-2500:], "{noformat}"]
    lines += ["", "h3. Blast-radius evidence", "||Source||Detail||"]
    for e in evs[:15]:
        lines.append(f"|{e.get('source')}|{str(e.get('detail')).replace('|', '/')}|")
    if blast.get("unresolvedSymbols"):
        lines += ["", f"_Graph blind spots (symbols with no Code Knowledge data): {', '.join(blast['unresolvedSymbols'][:10])}_"]
    if target.get("note"):
        lines += ["", f"_Routing: {target['note']}_"]
    lines += ["", "_Auto-generated by shockwave blast-radius triage._"]

    labels = ["blast-radius-auto", dedupe_label(src, commit, f"{verdict['org']}/{verdict['repo']}")]
    if verdict["verdict"] == "NeedsReview":
        labels.append("needs-review")
    fields = {
        "project": {"key": target.get("project")},
        "issuetype": {"name": "Story"},
        "summary": f"[Blast Radius] {src}@{short} may impact {verdict['org']}/{verdict['repo']}",
        "description": "\n".join(lines),
        "labels": labels,
    }
    if target.get("component"):
        fields["components"] = [{"name": target["component"]}]
    if target.get("assignee"):
        fields["assignee"] = {"name": target["assignee"]}
    return {"fields": fields, "linkedPrOrCommit": pr_url or commit_url}


class JiraClient:
    def __init__(self, cfg: Config = CONFIG):
        if not cfg.jira_pat:
            raise RuntimeError("JIRA_PAT not configured")
        self.base = cfg.jira_base.rstrip("/")
        self.h = {"Authorization": f"Bearer {cfg.jira_pat}", "Content-Type": "application/json", "Accept": "application/json"}

    def _do(self, method, path, body=None):
        rq = urllib.request.Request(self.base + path, data=json.dumps(body).encode() if body is not None else None, headers=self.h, method=method)
        try:
            with urllib.request.urlopen(rq, context=_CTX, timeout=60) as r:
                raw = r.read().decode()
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as e:
            raise RuntimeError(f"Jira {method} {path} -> HTTP {e.code}: {e.read().decode()[:400]}") from e

    def find_by_label(self, label: str) -> str | None:
        q = urllib.parse.urlencode({"jql": f'labels = "{label}"', "fields": "key", "maxResults": 1})
        d = self._do("GET", f"/rest/api/2/search?{q}")
        return d["issues"][0]["key"] if d.get("issues") else None

    def create(self, fields: dict) -> str:
        return self._do("POST", "/rest/api/2/issue", {"fields": fields})["key"]

    def comment(self, key: str, body: str):
        self._do("POST", f"/rest/api/2/issue/{key}/comment", {"body": body})


def create_one(verdict: dict, blast: dict, event: dict | None, cfg: Config = CONFIG, dry_run: bool = True,
               mapping: dict | None = None, project_override: str | None = None, jira: JiraClient | None = None) -> dict | None:
    if verdict["verdict"] not in ("Impacted", "NeedsReview"):
        return None
    mapping = mapping if mapping is not None else load_mapping(cfg.jira_mapping_file)
    target = resolve_target(verdict, mapping, cfg, project_override)
    payload = render(verdict, blast, event, target, cfg)
    f = payload["fields"]
    ticket = {"key": None, "summary": f["summary"], "assignedTeam": verdict.get("team"), "url": None,
              "linkedPrOrCommit": payload["linkedPrOrCommit"], "repo": f"{verdict['org']}/{verdict['repo']}",
              "verdict": verdict["verdict"], "project": target["project"], "component": target.get("component"),
              "dryRun": dry_run, "action": "dry-run", "payload": payload}
    if dry_run:
        return validate_jira_ticket(ticket)
    if not target["project"]:
        ticket.update(action="skipped", error="no Jira project resolved (set jira-team-mapping.yaml default.project or --project)")
        return validate_jira_ticket(ticket)
    jira = jira or JiraClient(cfg)
    dl = next(l for l in f["labels"] if l.startswith("br-"))
    existing = jira.find_by_label(dl)
    if existing:
        jira.comment(existing, f"Blast-radius re-run for the same change. Verdict: *{verdict['verdict']}*.\n\n{verdict['reasoning']}")
        key, action = existing, "commented"
    else:
        key, action = jira.create(f), "created"
    ticket.update(key=key, url=f"{cfg.jira_base.rstrip('/')}/browse/{key}", action=action)
    ticket.pop("payload", None)
    return validate_jira_ticket(ticket)


def create_all(verdicts: list[dict], blast: dict, event: dict | None, tests=None, cfg: Config = CONFIG,
               dry_run: bool = True, project_override: str | None = None) -> list[dict]:
    mapping = load_mapping(cfg.jira_mapping_file)
    jira = None if dry_run else JiraClient(cfg)
    out = []
    for v in verdicts:
        try:
            t = create_one(v, blast, event, cfg, dry_run, mapping, project_override, jira)
        except Exception as e:
            t = {"key": None, "summary": f"[Blast Radius] {v['org']}/{v['repo']}", "repo": f"{v['org']}/{v['repo']}",
                 "verdict": v["verdict"], "action": "error", "error": str(e)[:400]}
        if t:
            out.append(t)
    return out

